config/routes.rb
Rails.application.routes.draw do
  get '/concerts/list' => 'concerts#show_all_by_month' , as: 'list_by_month'
  get '/' => 'concerts#index' , as: 'front_page'
  get '/search' => 'concerts#search_form', as: 'search_price' 
  post '/search' => 'concerts#search_by_price', as: 'search_price_under' 
  get '/most_commented' => 'concerts#most_commented', as: 'most_commented'
  resources :concerts do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :concert, counter_cache: true
  validates :user, :comment, presence: true 


  has_attached_file :avatar, :url => "http://www.praize.com/forum/icons/users/31-user_icon-1.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  has_many :comments
  validates :venue, :band, :city, :price, :date, :description, presence: true 


  def self.show_concerts(number)
    order(date: :asc).limit(number)
  end

  def self.show_concerts_by_price(price)
    where("price < ?", price).order(price: :asc)
    
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "concert_network_layout"
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @concert = Concert.find_by(id: params[:concert_id])
    @comments = @concert.comments

  end

  def new
    @concert = Concert.find_by(id: params[:concert_id])
    @comment = @concert.comments.new
  end

  def create
    @concert = Concert.find_by(id: params[:concert_id])
    @comment = @concert.comments.new comment_params

    if @comment.save
      flash[:notice] = 'The comment was created successfully'
      redirect_to concert_path(@concert.id)
    else
      @errors = @comment.errors.full_messages
      flash.now[:alert] = "The comment can't be created"
      render 'new'
    end
  end

  def edit
    @concert = Concert.find_by(id: params[:concert_id])
    @comment = @concert.comments.find params[:id]
  end

  def update
    @concert = Concert.find_by(id: params[:concert_id])
    @comment = @concert.comments.find params[:id]

    if @comment.update_attributes comment_params
      redirect_to concert_comments_path(@concert.id)
    else
      @errors = @comment.errors.full_messages
      render 'edit'
    end
    
  end

  def destroy
    @concert = Concert.find_by(id: params[:concert_id])
    @comment = @concert.comments.find params[:id]

    @comment.destroy
    redirect_to concert_path(@concert.id)
    
  end

  private
  def comment_params
    params.require(:comment).permit(:user, :comment, :avatar)
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  

  def index
    
    @concerts_today =  Concert.where(:date => Date.today)
    @concerts_this_month = Concert.order(date: :asc).where(:date => Date.today..Date.today.end_of_month) - @concerts_today


    if @concerts_today.empty?
      render template: 'concerts/no_concerts'
    end
    
  end

  def most_commented
    @concerts = Concert.where("comments_count > ?", 0).order(comments_count: :desc).limit(5)
    @concerts_this_month = Concert.order(date: :asc).where(:date => Date.today..Date.today.end_of_month)
  end

  def search_form
    @concerts_this_month = Concert.order(date: :asc).where(:date => Date.today..Date.today.end_of_month)
    
  end

  def search_by_price
    @concerts = Concert.show_concerts_by_price params[:price]
    @concerts_this_month = Concert.order(date: :asc).where(:date => Date.today..Date.today.end_of_month)

    if @concerts.empty?
      render template: 'concerts/no_concerts'
    end
    
  end

  def show_all_by_month
    @concerts = Concert.order(date: :asc)
    @concerts_today =  Concert.where(:date => Date.today)
    @concerts_this_month = Concert.order(date: :asc).where(:date => Date.today..Date.today.end_of_month) - @concerts_today
    
    if @concerts.empty?
      render template: 'concerts/no_concerts'
    end
    render 'list_by_month'
  end


  def show
    @concert = Concert.find_by(id: params[:id])
    @comments = @concert.comments
    unless @concert
      render 'no_concert_found'
    end
  end

  def new
    @concert = Concert.new
  end

  def create
    @concert = Concert.new concert_params
    

    if @concert.save
      flash[:notice] = 'The concert was created successfully'
      redirect_to concerts_path
    else
     @errors = @concert.errors.full_messages
     flash.now[:alert] = "The concert can't be created"
     render 'new'
    end
  end


  def edit
    @concert = Concert.find params[:id]
   
  end

  def update
    @concert = Concert.find params[:id]
    

    if @concert.update_attributes concert_params
      redirect_to front_page_path(@concert.id)
    else
      @errors = @concert.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @concert = Concert.find params[:id]


    @concert.destroy
    redirect_to concerts_path
    
  end


  private
  def concert_params
    params.require(:concert).permit(:date, :band, :venue, :city, :price, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_flash_message
    display_message(:alert)||display_message(:notice)
  end

  def display_message(type)
    if flash[type] 
      content_tag :div, class: type do
        content_tag :p do
          flash[type]
        end 
      end 
    end 
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/comments/new.html.erb
<h2>
  Create a new comment for the concert:<br>
   <%= @concert.band %> of <%= @concert.date.strftime("%d - %m - %Y") %> at 
   <%= @concert.venue %>, <%= @concert.city %>
</h2>

<% if @errors.present? %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %> 
  </ul>
<% end %>

<%= display_flash_message %>



<%= form_for [@concert, @comment], :html => {:multipart => true} do |f|%>

  <div class="new_concert_form">
  

    <%= f.label :user %>
    <%= f.text_field :user %> 
    <br>
    <%= f.label :comment %>
    <%= f.text_area :comment %> 


  </div>

  <div class='create_concert_button'>
    <%= f.submit "Add your comment" %>
  </div>


  

<% end %>

<br>
<%= link_to 'Back to concert details', concert_path(@concert.id) %>
<%= link_to 'Back to the list of concerts for today', front_page_path %>

app/views/concerts/_concerts_layout.html.erb
<%= content_tag :div, class: "concerts_this_month col-md-4" do%> 
  <h4>This month's next concerts:</h4>
  <% @concerts_this_month.each do |concert| %>
    <%= content_tag :div, class: "concerts_this_month" do%> 
      <p><%= link_to concert.band, concert_path(concert.id)%> day <%= concert.date.strftime("%d - %m - %Y")   %></p>

    <% end %>
  <% end %>
<% end %>





<%= display_flash_message %>

app/views/concerts/_form.html.erb
<% if @errors.present? %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %> 
  </ul>
<% end %>

<%= display_flash_message %>



<%= form_for @concert do |f|%>

  <div class="new_concert_form">
    <%= f.label :date %>
    <%= f.date_field :date %> 

    <%= f.label :band %>
    <%= f.text_field :band %> 

    <%= f.label :venue %>
    <%= f.text_field :venue %> 
    
    <%= f.label :city %>
    <%= f.text_field :city %> 
   
    <%= f.label :price %>
    <%= f.text_field :price %> 

    <%= f.label :description %>
    <%= f.text_area :description %> 
  </div>

  <div class='create_concert_button'>
    <%= f.submit "Add the concert and rock'n roll!!!" %>
  </div>


  

<% end %>

<br>
<%= link_to 'Back to the list of concerts for today', front_page_path %>

app/views/concerts/edit.html.erb
<h2>Editing a concert</h2>

<%= render 'form' %>

app/views/concerts/index.html.erb
<%= content_tag :div, class: "concerts_today col-md-8" do%> 
    
  <% @concerts_today.each do |concert| %>
    <div class = 'concert_today_details'>
      <p class="lead">Concerts for <%= Date.today.strftime("%A, %d - %B - %Y") %></p>
      
      <div class = "concert_details col-md-8">
        <p ><%= concert.band %></p>
        <p>at <%= concert.venue %>, <%= concert.city %></p>
        <p>Price: <%= concert.price %>€</p>
        <p><%= concert.description %></p>
      </div>

      <div class="col-md-4">
        <div>
          <img src="" alt="here comes the photo">
        </div>
        <div class='concert_details_tools'>
          <p style = "text-align: center">
            <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
            <%= link_to 'Comment', new_concert_comment_path(concert.id) %>
          </p>

          <p style = "text-align: center">
            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
            <%= link_to 'Edit', edit_concert_path(concert.id) %>
          </p>
            
        </div>
      </div>
      

    </div>
  <% end %>

<% end %>


<%= render 'concerts_layout' %>

app/views/concerts/list_by_month.html.erb
<%= content_tag :div, class: "concerts_list col-md-8" do %> 
  <p class="lead bg-danger">Concerts for <%= Date.today.strftime("%Y") %></p>
  <% @concerts.each do |concert| %>
    <div class = 'concert_today_details'>
      <div class = "concert_details col-md-8">
        <p ><%= concert.band %> at <%= concert.venue %>, <%= concert.city %></p>
        <p ><%= concert.date.strftime("%A, %d - %m") %>. Price <%= concert.price %>€</p>
        <p><%= concert.description %></p>
        <p><%= concert.comments.count %></p>

      </div>

      <div class="col-md-4">
        <div class='concert_details_tools'>
          <p style = "text-align: center">
            <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
            <%= link_to 'Comment', new_concert_comment_path(concert.id) %>
          </p>

          <p style = "text-align: center">
            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
            <%= link_to 'Edit', edit_concert_path(concert.id) %>
          </p>
            
          <p style = "text-align: center">
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <%= link_to 'Details', concert_path(concert.id) %>
          </p>
            
        </div>
      </div>

    </div>
  <% end %>

<% end %>


<%= render 'concerts_layout' %>

app/views/concerts/most_commented.html.erb
<%= content_tag :div, class: "concerts_list col-md-8" do%> 
    
  <p class="lead">Most commented concerts <%= params[:price] %></p>
  <% for counter in 1..@concerts.maximum(:comments_count) do %>
  <% @concert_counter = @concerts.where(comments_count: counter) %>
  <%= binding.pry    %>
    <% @concert_counter.each do |concert| %>
    <div class = 'concert_today_details'>
      <p class="lead">With <%= counter %> comments</p>
      
      <div class = "concert_details col-md-8">
        <p ><%= concert.band %></p>
        <p ><%= concert.date %></p>
        <p>at <%= concert.venue %>, <%= concert.city %></p>
        <p>Price: <%= concert.price %>€</p>
        <p><%= concert.description %></p>
      </div>

      <div class="col-md-4">
        <div>
          <img src="" alt="here comes the photo">
        </div>
        <div class='concert_details_tools'>
          <p style = "text-align: center">
            <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
            <%= link_to 'Comment', new_concert_comment_path(concert.id) %>
          </p>

          <p style = "text-align: center">
            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
            <%= link_to 'Edit', edit_concert_path(concert.id) %>
          </p>

          <p style = "text-align: center">
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <%= link_to 'Details', concert_path(concert.id) %>
          </p>
            
        </div>
      </div>
      

    </div>
    <% end %>
  <% end %>

<% end %>


<%= render 'concerts_layout' %>

app/views/concerts/new.html.erb
<h2>Create a new concert</h2>

<%= render 'form' %>

app/views/concerts/no_concert_found.html.erb
<%= content_tag :div, class: "concerts_today col-md-8" do %> 
    <h1 class="container">There are no concerts with that name!</h1>
    
<% end %>

<%= render 'concerts_layout' %>

app/views/concerts/no_concerts.html.erb
<%= content_tag :div, class: "concerts_today col-md-8" do %> 
    <h1>There are no concerts for your search!</h1>
<% end %>

<%= render 'concerts_layout' %>

app/views/concerts/search_by_price.html.erb
<%= content_tag :div, class: "concerts_list col-md-8" do%> 
    
  <p class="lead">Concerts under <%= params[:price] %></p>
  <% @concerts.each do |concert| %>
    <div class = 'concert_today_details'>
      
      <div class = "concert_details col-md-8">
        <p ><%= concert.band %></p>
        <p ><%= concert.date %></p>
        <p>at <%= concert.venue %>, <%= concert.city %></p>
        <p>Price: <%= concert.price %>€</p>
        <p><%= concert.description %></p>
      </div>

      <div class="col-md-4">
        <div>
          <img src="" alt="here comes the photo">
        </div>
        <div class='concert_details_tools'>
          <p style = "text-align: center">
            <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
            <%= link_to 'Comment', new_concert_comment_path(concert.id) %>
          </p>

          <p style = "text-align: center">
            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
            <%= link_to 'Edit', edit_concert_path(concert.id) %>
          </p>
            
        </div>
      </div>
      

    </div>
  <% end %>

<% end %>


<%= render 'concerts_layout' %>

app/views/concerts/search_form.html.erb
<% if @errors.present? %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %> 
  </ul>
<% end %>

<%= display_flash_message %>

<form action='' method='POST'>
  <p>
    <label for= "price">Price under:</label>
    <input type="text" name="price"><br>
  </p>
  <p>
    <%= button_to "Search concerts!", search_price_under_path %>
  </p>

</form> 

<br>
<%= link_to 'Back to the list of concerts for today', front_page_path %>


<%= render 'concerts_layout' %>

app/views/concerts/show.html.erb
<%= content_tag :div, class: "concert_details" do%> 

      <h3><%= @concert.band %></h3>
      <h6>Next <%= @concert.date.strftime("%d - %m - %Y") %></h6>
      <ul>
        <li>At <%= @concert.venue %>, <%= @concert.city %></li>
        <li>Price: <%= @concert.price %>€</li>
        <li><%= @concert.description %></li>
      </ul>

<% end %>

<%= link_to('Delete concert', concert_path(@concert.id), method: :delete, data: {confirm: 'Are you sure'})  %>
<%= link_to 'Edit this concert', edit_concert_path(@concert.id) %>
<%= link_to 'Back to concerts list', front_page_path %>

<div class="detailBox">
  <div class="titleBox">
    <label class="col-md-8">Comments</label>
    <form class="" role="form">
        <div class='create_concert_button'>
          <%= link_to 'Add your comment', new_concert_comment_path(@concert.id) %>
        </div>
    </form>
  </div>

  <% @comments.each do |comment| %>
    <div class="actionBox">
      <ul class="commentList">
        <li>
          <div class="commenterImage">
            <%= image_tag '31-user_icon-1', class: "avatar_comment" %>
          </div>
          <div class="commentText">
        
            <span class="comment_user"><%= comment.user %> said </span>
            <span class="date sub-text">
              <%= comment.created_at.strftime("%d - %m, %Y") %>
            </span>  
            <br>
            <p class=""><%= comment.comment %></p> 
             

          </div>
        </li>

      <%= link_to('Delete comment', concert_comment_path(@concert.id, comment.id), method: :delete, data: {confirm: 'Are you sure'})  %>
      <%= link_to 'Edit', edit_concert_comment_path(@concert.id, comment.id) %>
  
      </ul>
    </div>

  <% end%>
</div>

<%= display_flash_message %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concertnetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/concert_network_layout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <title>Welcome to the Concert Network!</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>

<body>

  <div>
    <img src='http://www.aem2.org/wp-content/uploads/2013/03/1187835662_Concert1_1280x1024_13.jpg' class="bg" alt="background">
  </div>

    <header class="header col-md-12">
      <div>This is the header of the concert network</div>
      <div class="dropdown pull-right">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Options <span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li><a tabindex="-1"><%= link_to "Today's concert", front_page_path %></a></li>
          <li><a tabindex="-1"><%= link_to "List of Concerts", list_by_month_path %></a></li>
          <li class="divider"></li>
          <li><a tabindex="-1"><%= link_to "New concert", new_concert_path %></a></li>
          <li><a tabindex="-1"><%= link_to "Price search", search_price_path %></a></li>
          <li><a tabindex="-1"><%= link_to "Most commented", most_commented_path %></a></li>

        </ul>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>

    <footer class="footer col-md-8 col-md-offset-2 clearfix" >  
      <div>This is the footer of the concert network</div>
    </footer>  


</body>

</html>